### ISSUE TITLE
Would it be better to use RGB images as input?

### ISSUE THREAD

**Issue by fengmoumou123** [ethz-asl/hfnet#17]
Hi, author. I want to ask that would it be better to use RGB images as input?Have you tried this yet?

**Comment by freedogge** [comment]
Hey, friend. I had some problems for many days. Could you give some advice?
I can't build the dependence of hloc-cpp.
My operating system is ubuntu 16.04, and I also build catkin_simple ,  eigen_catkin, gflags_catkin, pybind11_catkin and etc... 
But some errors accured.
1. I can't find .so files in opengv(opengv has been built), because of this, pybind11_catkin can't find opengv.
2. My pybind11_catkin can't work. How to generate the pyd file? I can only get .so file. 
How did you do it?  

By the way, whether hfNet depends on ROS-python? My python environment is built by anaconda......   Conda and ROS are difficult to work together.

Thanks in advance!!!

**Comment by Skydes** [comment]
@fengmoumou123 We did some early experiments training HF-Net with RGB images instead of grayscale, and that led to lower performance of the local descriptor and detector. We did not investigate this further.
