### ISSUE TITLE
sqlite3.OperationalError: no such table: two_view_geometries

### ISSUE THREAD

**Issue by xiaoxiaowenge-work** [ethz-asl/hfnet#48]
Hello, Mr. Sariln! thanks for selfless dedication.
In colmap-helpers.  When I run :  match_features_with_db_prior.py. 
get some errors
`File "match_features_with_db_prior.py", line 80, in <module>
    main()
  File "match_features_with_db_prior.py", line 39, in main
    args.database_file, args.min_num_matches, args.image_prefix)
  File "/hf_net/colmap-helpers/internal/db_matching_images.py", line 59, in get_matching_images
    (min_num_matches,))
sqlite3.OperationalError: no such table: two_view_geometries
`

Is it because this aachen.db  file  is new (2020.4), so this table  " two_view_geometries" is not included

**Comment by sarlinpe** [comment]
It seems that the table `two_view_geometries` was initially called `inlier_matches`, but it was changed in COLMAP about two years ago https://github.com/colmap/colmap/commit/9ff05fc3f87e58b332be3684f78cb80d88ce0f89. For some reason the provided `aachen.db` (and RobotCar's `overcast-reference.db`) uses the old naming. I don't know if I manually renamed the table when working on HFNet (you can do this too with Python `sqlite3`), or maybe the database was changed since then.

We have released a new toolbox for SfM and visual localization called hloc: https://github.com/cvg/Hierarchical-Localization/ It can essentially do the same as the scripts in `hfnet/colmap-helpers`, but in a cleaner, user-friendly way. hloc can also do much more: run SfM for your own dataset, run localization on InLoc, with SuperGlue, our new feature matcher.

**Comment by xiaoxiaowenge-work** [comment]
thanks very much, great work
